function title_str = plotting_getStandardTitle(S_coeffs)
    k_a = S_coeffs.k_a;
    n_R = real(S_coeffs.n);
    n_I = imag(S_coeffs.n);
    nCF = S_coeffs.nCF;
    g_per = S_coeffs.g_per;
    g_par = S_coeffs.g_par;
    %eps   = S_coeffs.eps;
    
    title_str = ['ka='  , num2str(k_a,'%.2f'), ...
                 ' nR=' , num2str(n_R,'%.1f'), ...
                 ' nI=' , num2str(n_I,'%.1e'), ...
                 ' nCF=', num2str(nCF,'%d'), ...
                 ' gpe=', num2str(g_per,'%.4e'), ...
                 ' gpa=', num2str(g_par,'%.4e')]; %, ...
                 %' eps=', num2str(eps,')];
end